### ISSUE TITLE
how can i use the tas server?

### ISSUE THREAD

**Issue by gamerbross** [fruityloops1/smo-practice#12]

**Comment by fruityloops1** [comment]
Compile the server and run it, if you are on windows use [MonsterDruide1's server](https://github.com/MonsterDruide1/smo-practice-server), uncomment [this line](https://github.com/fruityloops1/smo-practice/blob/36bf46b276947729b8c580bb7de1cea8e209150f/source/fl/ui.cpp#L412) and replace "someip" with the ip that your server is running at. Compile the mod and send it to your switch, make sure that the server ports (7902, 7901) are available to the switch and click "connect to server" ingame.

**Comment by gamerbross** [comment]
> Compile the server and run it, if you are on windows use [MonsterDruide1's server](https://github.com/MonsterDruide1/smo-practice-server), uncomment [this line](https://github.com/fruityloops1/smo-practice/blob/36bf46b276947729b8c580bb7de1cea8e209150f/source/fl/ui.cpp#L412) and replace "someip" with the ip that your server is running at. Compile the mod and send it to your switch, make sure that the server ports (7902, 7901) are available to the switch and click "connect to server" ingame.

how i can compile the mod on windows (sorry if im bothering)

**Comment by gamerbross** [comment]
> Compile the server and run it, if you are on windows use [MonsterDruide1's server](https://github.com/MonsterDruide1/smo-practice-server), uncomment [this line](https://github.com/fruityloops1/smo-practice/blob/36bf46b276947729b8c580bb7de1cea8e209150f/source/fl/ui.cpp#L412) and replace "someip" with the ip that your server is running at. Compile the mod and send it to your switch, make sure that the server ports (7902, 7901) are available to the switch and click "connect to server" ingame.

i get this error when i install keystone
`error: command C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

**Comment by fruityloops1** [comment]
I can't help you with python problems, you are more likely to get help on the [SMO Modding Discord](https://discord.com/invite/u2dfaQpDh5).
