### ISSUE TITLE
Don't know how to build?

### ISSUE THREAD

**Issue by GoatGod64** [fruityloops1/smo-practice#13]
I'm really stupid and don't know how to build the mod even with the instructions.

Can someone help me?

**Comment by fruityloops1** [comment]
Do you actually want to change the source code of the mod? If not, there is pre-built releases [here](https://github.com/fruityloops1/smo-practice/releases)

**Comment by GoatGod64** [comment]
I've tried other builds and I still don't know what to do. Can you make a tutorial video?

**Comment by fruityloops1** [comment]
What do you mean by "other builds"?

**Comment by GoatGod64** [comment]
I meant pre releases

**Comment by MonsterDruide1** [comment]
Well, there are no other commits/things done since the last release. Building it yourself will have no value over using prebuilt releases.
