### ISSUE TITLE
Noob questions

### ISSUE THREAD

**Issue by DermXZ** [fruityloops1/smo-practice#24]
1- i use atmosphere and smo 1.3, what i have to do with the .elf file?
2- what the moon refresh option does? I used in a new file and when i arrived to sand kingdom i have a lot of moons
Thanks!

**Comment by fruityloops1** [comment]
The elf file is just to confirm I haven't made any modifications to the mod before uploading the build.
The moon refresh option is supposed to refresh your moons after reloading a stage, use [the 1.3 fork](https://github.com/Ontwikseltsaar/smo-practice) if you are playing on 1.3.
