### ISSUE TITLE
Problem changing options in the second view

### ISSUE THREAD

**Issue by DermXZ** [fruityloops1/smo-practice#25]
After i disable the menu and enable again, i can't change the options in the second view, like teleport, etc.

**Comment by MonsterDruide1** [comment]
Which version of the game/mod are you playing on?

**Comment by DermXZ** [comment]
1.3

**Comment by fruityloops1** [comment]
Use [this fork](https://github.com/Ontwikseltsaar/smo-practice) for 1.3
