### ISSUE TITLE
Yuzu support?

### ISSUE THREAD

**Issue by Briancbn** [fruityloops1/smo-practice#4]
I understand it is not stated in the README, but I would hope to get Yuzu support too.

Here is my Yuzu folder structure in the mod load directory.
```
├── practice_mod
│   ├── exefs
│   │   └── subsdk1    <-- smo-practice100.nso
│   ├── romfs
│   │   ├── DebugData
│   │   │   └── Font
│   │   │       ├── nvn_font_jis1.ntx
│   │   │       ├── nvn_font_jis1_tbl.bin
│   │   │       ├── nvn_font.ntx
│   │   │       ├── nvn_font_shader.bin
│   │   │       └── nvn_font_shader_jis1.bin
│   │   └── LayoutData
│   │       └── CounterCoin.szs
│   └── romfs_ext
│       └── startlight_patch_100
│           └── 3CA12DFAAF9C82DA064D1698DF79CDA1.ips
```
I have also tried placing `3CA12DFAAF9C82DA064D1698DF79CDA1.ips` in the `exefs` and `romfs`, with and without the `startlight_patch_100` folder, but none of it works. Here is what I get from the yuzu, just `ABCD` on the left corner, I am not familiar with the Yuzu debugger also.

![image](https://user-images.githubusercontent.com/15899525/147523977-0eb26f90-cf24-4f9e-bdbb-f766b4edefac.png)

### Version
- **System**: Ubuntu 20.04
- **Yuzu**: yuzu-mainline tag `mainline-0-835`, build from source
- **SMO Version**: 1.3.0
- **Mod Version**: 1.2.0, build from source

I am not sure if this is an issue on the Yuzu side or the mod side. As [this early mod](https://brycewithfiveunderscores.com/mods/smo/movement-practice/) works perfectly on Yuzu. If you would point me to the right direction, I can also help to contribute to the Yuzu support for this mod.

**Comment by fruityloops1** [comment]
You compiled the 1.0 version and tried to use it on 1.3, to compile for 1.3 you must set `S2VER` and `S2VERSTR` in the Makefile to `130` and `1.3.0`.
The `DebugData` folder is needed on 1.0 only, and the `LayoutData` folder is needed on 1.3 only, since a different method of displaying text is used in 1.3.

**Comment by Briancbn** [comment]
Thanks @fruityloops1, I managed to get it working with the following folder structure

```
├── practice_mod
│   ├── exefs
│   │   ├── B424BE150A8E7D78701CBE7A439D9EBF.ips
│   │   └── subsdk1    <-- smo-practice130.nso
│   └── romfs
│       └── LayoutData
│           └── CounterCoin.szs
```
Works like a charm now.

![image](https://user-images.githubusercontent.com/15899525/147623668-275238cb-b86e-479f-ac79-b6949488c78c.png)

Do you mind me submitting a PR to include a Yuzu setup instruction in the README?

**Comment by fruityloops1** [comment]
That would be a good idea.

**Comment by MonsterDruide1** [comment]
The PR has been accepted and the description can now be found in the `README`, so this issue can be closed.
